### ISSUE TITLE
Usar o Design Pattern Strategy ara solucionar o problema dos Endpoints

### ISSUE THREAD

**Issue by vitorsilverio** [vitorsilverio/libraryapi#53]
A ideia é ter apenas um endpoint responsável pela ação comum evitando repetição de código.
O tipo de resposta deve ser pedido por um parametro GET ou pelo proprio Http Header Accept dando prioridade para o get param.
Além disso utilizando design pattern Strategy  será possível implementar novos formato que forem necessários

```
curl "http://localhost/api/v2/pergamum/{id}" -H "Accept: application/marc" -H "Server: https://pergamum.ufsc.br/pergamum"
#permitindo também via get params
curl "http://localhost/api/v2/pergamum/{id}?server=https://pergamum.ufsc.br/pergamum&accept=application/xml"

```
A ideia é manter as urls anteriores por um tempo mas descontinuar para esse novo modelo
O que acha @jaideraf ?

**Comment by jaideraf** [comment]
Acho interessante, mas não se esqueça de que na solicitação de `application/marc` ou de `text/plain` deve ser aplicada a função  `util.attach_file`, mas em `application/xml`, não, para não gerar arquivo de download.

> A ideia é manter as urls anteriores por um tempo mas descontinuar para esse novo modelo

Perfeito, até porque, neste exato momento, estou usando essa estrutura em produção.

Já que vamos mudar, estive pensando que é melhor usar a URL *quase* completa do web service. Atualmente passamos algo como `https://pergamum.ufsc.br/pergamum/` e a aplicação completa o endereço com `/web_service/servidor_ws.php?wsdl`, porém, pelo que estou percebendo essa URL inicial muda muito em cada instalação do Pergamum, então acho melhor passar o endereço quase completo já, até antes da query string `?wsdl`. Assim: https://pergamum.ufsc.br/pergamum/web_service/servidor_ws.php

É bom que esse endereço tem até um inferfacezinha de documentação (clique nele).

**Comment by jaideraf** [comment]
Talvez seja bom também criar comportamentos default, por exemplo, se não for passado o parâmetro (ou o header) de `accept`, então o resultado padrão será o do `application/marc`, que é o formato mais utilizado pelos catalogadores.

**Comment by vitorsilverio** [comment]
> Talvez seja bom também criar comportamentos default, por exemplo, se não for passado o parâmetro (ou o header) de `accept`, então o resultado padrão será o do `application/marc`, que é o formato mais utilizado pelos catalogadores.

O comportamento padrão estava prevendo, o normal para API seria o Json, mas esse é um provider que não temos no momento, Estava vendo se pelo fastapi tem como ter Header / Query param com mesmo nome de forma simples, mas precisarei testar.
 Quanto a questão dos Providers serem attach files isso tudo bem a ideia era ter uma função tipo:
```
def xxxx_provider(Record) -> Response:
  ## Toda a logica para a transformação
  return ....
```
e depois um dict que para cada formato aplicasse a função certa, bastando sempre que quiser adicionar um novo formato criar uma função nova e adicionasse a esse dict. Resumindo: Design Pattern Strategy é isso

**Comment by jaideraf** [comment]
> O comportamento padrão estava prevendo, o normal para API seria o Json, mas esse é um provider que não temos no momento,

Pode ser o formato XML por padrão, esse que temos. Não é muito usado mas... fica com mais cara de API.
