### ISSUE TITLE
Opção application/marc quebra a página html do catálogo

### ISSUE THREAD

**Issue by jaideraf** [vitorsilverio/libraryapi#89]
Ao tentar substituir a versão antiga (v1) pela versão nova (v2) aqui (opção "exportar"):
https://pergamum.ufsc.br/pergamum/biblioteca/index.php?word=os%20miser%C3%A1veis

Isto é, substituir o URL do tipo 
https://libraryapi.sites.ufsc.br/pergamum/mrc?url=https://pergamum.ufsc.br/pergamum&id=226347
pelo 
https://libraryapi.sites.ufsc.br/api/v2/pergamum/226347?url=https://pergamum.ufsc.br/pergamum/web_service/servidor_ws.php&media_type=application/marc

por alguma razão que desconheço, a opção `application/marc` faz a página congelar. Isso não acontece com `application/xml` ou `text/plain`, por exemplo.
![marc-congela-tela](https://user-images.githubusercontent.com/3636594/171465824-f3d64caf-fbf0-4749-8468-b620cf26a436.png)

Se quiser testar, use o console do navegador: 

```javascript
const pmu_linha_top = document.querySelectorAll(".pmu_linha_top");
for (let elem of pmu_linha_top) {
  let codAcervo = elem.parentElement.firstElementChild.lastChild.textContent;
  let libraryApiParams = "?url=https://pergamum.ufsc.br/pergamum/web_service/servidor_ws.php&media_type=application/marc"
  let exportUrl = "<a href='https://libraryapi.sites.ufsc.br/api/v2/pergamum/" + codAcervo + libraryApiParams + "' class='link_azul_claro' target='_blank' title='Salvar MARC ISO 2709'>(exportar)</a>";
  for (let aElem of elem.children) {
    if (aElem.matches('a[href*="marc"]')) {
      aElem.insertAdjacentHTML("afterend", exportUrl);
    }
  }
}
```

E é justamente o formato `application/marc` que precisa funcionar. Não entendi o que pode estar dando errado, talvez seja necessário mudar o formato padrão (sem especificar o param `media_type`) para o `marc_provider`, em vez do `json_provider` aqui: 
https://github.com/vitorsilverio/libraryapi/blob/main/app/main.py#L67

O que acha?

**Comment by vitorsilverio** [comment]
Já tentou criar o elemento com:
```javascript
let exportUrl = document.createElement('a')
exportUrl.href = `https://libraryapi.sites.ufsc.br/api/v2/pergamum/${codAcervo}${libraryApiParams}`
exportUrl.classList.add('link_azul_claro')
exportUrl.target='_blank'
exportUrl.title='Salvar MARC ISO 2709'
exportUrl.appendChild(document.createTextNode('(exportar)'))
```
E trocar o `aElem.insertAdjacentHTML("afterend", exportUrl);`
por ```
aElem.appendChild(exportUrl)
```
